workflows:
    ios app archive workflow:
      scripts:
        - name: Install npm dependencies for Ionic project
          script: |
            npm install
        - name: Cocoapods installation
          script: |
            cd ios/App && pod install
        - name: Update dependencies and copy web assets to native project
          script: |
            # npx cap copy # <- use this is you don't need to update native dependencies
            npx cap sync # <- update native dependencies and copy web assets to native project
        #- name: Add provisioning profiles
        #  script: |
        #    set -e # exit on first failed command

        #    PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
        #    mkdir -p "$PROFILES_HOME"
        #    echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
        #- name: Add signing certificate
        #  script: |
        #    set -e # exit on first failed command

        #    echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
        #    keychain initialize
        #    keychain add-certificates \
        #        --certificate /tmp/certificate.p12 \
        #        --certificate-password ${CERTIFICATE_PASSWORD?}

        - name: Increment build number
          script: | 
            #!/bin/sh
            set -e
            set -x
            cd $CM_BUILD_DIR
            cd ios/App
            agvtool new-version -all $BUILD_NUMBER
        #- name: Set up code signing settings on Xcode project
        #  script: xcode-project use-profiles
        - name: Build ipa for distribution
          script: |
            #!/bin/sh
            set -e
            set -x
            cd $CM_BUILD_DIR
            xcode-project build-ipa --workspace "${XCODE_WORKSPACE?}" --scheme "${XCODE_SCHEME?}"
      artifacts:
        - build/ios/ipa/*.ipa
      environment:
        ios_signing:
          provisioning_profiles:
            - ohsu
          certificates:
            - ohsu
        groups:
          - certificate_credentials
        vars:
          XCODE_WORKSPACE: "ios/App/App.xcworkspace"
          XCODE_SCHEME: "App"